//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int asi_id { get; set; }
        public System.DateTime asi_fecha { get; set; }
        public System.TimeSpan asi_hora_inicio { get; set; }
        public Nullable<System.TimeSpan> asi_hora_fin { get; set; }
        public int asi_tiempo { get; set; }
        public string asi_contenido { get; set; }
        public int asi_est_id { get; set; }
        public int asi_tema_id { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Tema Tema { get; set; }
    }
}
