//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario_Profesor
    {
        public int hor_pro_id { get; set; }
        public string hor_pro_dia { get; set; }
        public System.TimeSpan hor_pro_hora_inicio { get; set; }
        public System.TimeSpan hor_pro_hora_fin { get; set; }
        public string hor_pro_pro_id { get; set; }
    
        public virtual Profesor Profesor { get; set; }
    }
}
