//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesor()
        {
            this.Horario_Profesor = new HashSet<Horario_Profesor>();
            this.Profesor_Materia = new HashSet<Profesor_Materia>();
        }
    
        public string pro_id { get; set; }
        public string pro_nombre { get; set; }
        public string pro_apellido { get; set; }
        public string pro_telefono { get; set; }
        public string pro_direccion { get; set; }
        public string pro_correo { get; set; }
        public string pro_cedula { get; set; }
        public string pro_profesion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario_Profesor> Horario_Profesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profesor_Materia> Profesor_Materia { get; set; }
    }
}
